# -*- coding: utf-8 -*-
"""AI_UTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7qAid1yQ5a-nB-sjv5xZq2scIsh_h65
"""

!pip install experta

!pip install --upgrade frozendict

from experta import *

class Diagnosis(KnowledgeEngine):

    # Rules untuk diagnosis tanaman berdasarkan symptoms
    @Rule(Fact(Daun_menguning=True) & Fact(Bercak_hitam=True))
    def Penyakit_Bercak_Hitam(self):
        print("Diagnosis: Tanaman mengalami penyakit Jamur.")

    @Rule(Fact(Daun_menguning=True) & Fact(Daun_berlubang=True))
    def Penyakit_Daun_Berlubang(self):
        print("Diagnosis: Tanaman mengalami kerusakan akibat serangan hama seperti ulat.")

    @Rule(Fact(Daun_menguning=True) & Fact(Tanaman_layu=True))
    def Penyakit_Daun_Menguning(self):
        print("Diagnosis: Tanaman sedang mengalami layu, dapat disebabkan penyakit akar dan kutu daun.")

    @Rule(Fact(Tanaman_layu=True) & Fact(Bercak_hitam=True))
    def Penyakit_Layu_Bercak(self):
        print("Diagnosis: Tanaman mengalami layu dan bercak hitam, kemungkinan Thrips.")

def get_input():
    """Helper function to get user input as boolean (yes/no)."""
    def ask_question(question):
        return input(question + " (yes/no): ").strip().lower() == "yes"

    return {
        "Daun_menguning": ask_question("Apakah daun tanaman menguning?"),
        "Bercak_hitam": ask_question("Apakah ada bercak hitam pada daun?"),
        "Daun_berlubang": ask_question("Apakah daun tanaman berlubang?"),
        "Tanaman_layu": ask_question("Apakah tanaman menunjukkan gejala layu?"),
    }

# Running untuk expert system
if __name__ == "__main__":
    symptoms = get_input()
    engine = Diagnosis()
    engine.reset()  # reset untuk knowledge engine

    for symptom, present in symptoms.items():
        engine.declare(Fact(**{symptom: present}))  # deklarasi fakta

    engine.run()  # run untuk inference engine


#Penjelasan Alur inferensi
# A--> daun menguning, B --> bercak hitam, C--> daun berlubang, D --> tanaman layu.
# jika A & B --> B
# jika A & C --> C
# jika A & D --> A
# jika D & B --> D

# jika daun menguning dan bercak hitam maka daun bercak hitam akibat jamur
# jika daun menguning dan daun berlubang maka daun berlubang akibat ulat
# jika daun menguning dan tanaman layu maka daun menguning akibat kutu daun
# jika tanaman layu dan bercak hitam maka tanaman layu akibat thrips